# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"

sphinx:
   configuration: docs/conf.py

formats:
  - epub
  - pdf

python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .
