"""GraphQL Type System

The :mod:`graphql.type` package is responsible for defining GraphQL types and schema.
"""

from ..pyutils import Path as ResponsePath

# Uphold the spec rules about naming.
from .assert_name import assert_enum_value_name, assert_name
from .definition import (
    GraphQLAbstractType,  # Predicates; Assertions; Un-modifiers; Thunk handling; Definitions; Type Wrappers; Types; Keyword Args; Resolvers
)
from .definition import (
    GraphQLArgument,
    GraphQLArgumentKwargs,
    GraphQLArgumentMap,
    GraphQLCompositeType,
    GraphQLEnumType,
    GraphQLEnumTypeKwargs,
    GraphQLEnumValue,
    GraphQLEnumValueKwargs,
    GraphQLEnumValueMap,
    GraphQLField,
    GraphQLFieldKwargs,
    GraphQLFieldMap,
    GraphQLFieldResolver,
    GraphQLInputField,
    GraphQLInputFieldKwargs,
    GraphQLInputFieldMap,
    GraphQLInputObjectType,
    GraphQLInputObjectTypeKwargs,
    GraphQLInputType,
    GraphQLInterfaceType,
    GraphQLInterfaceTypeKwargs,
    GraphQLIsTypeOfFn,
    GraphQLLeafType,
    GraphQLList,
    GraphQLNamedInputType,
    GraphQLNamedOutputType,
    GraphQLNamedType,
    GraphQLNamedTypeKwargs,
    GraphQLNonNull,
    GraphQLNullableType,
    GraphQLObjectType,
    GraphQLObjectTypeKwargs,
    GraphQLOutputType,
    GraphQLResolveInfo,
    GraphQLScalarLiteralParser,
    GraphQLScalarSerializer,
    GraphQLScalarType,
    GraphQLScalarTypeKwargs,
    GraphQLScalarValueParser,
    GraphQLType,
    GraphQLTypeResolver,
    GraphQLUnionType,
    GraphQLUnionTypeKwargs,
    GraphQLWrappingType,
    Thunk,
    ThunkCollection,
    ThunkMapping,
    assert_abstract_type,
    assert_composite_type,
    assert_enum_type,
    assert_input_object_type,
    assert_input_type,
    assert_interface_type,
    assert_leaf_type,
    assert_list_type,
    assert_named_type,
    assert_non_null_type,
    assert_nullable_type,
    assert_object_type,
    assert_output_type,
    assert_scalar_type,
    assert_type,
    assert_union_type,
    assert_wrapping_type,
    get_named_type,
    get_nullable_type,
    is_abstract_type,
    is_composite_type,
    is_enum_type,
    is_input_object_type,
    is_input_type,
    is_interface_type,
    is_leaf_type,
    is_list_type,
    is_named_type,
    is_non_null_type,
    is_nullable_type,
    is_object_type,
    is_output_type,
    is_required_argument,
    is_required_input_field,
    is_scalar_type,
    is_type,
    is_union_type,
    is_wrapping_type,
    resolve_thunk,
)
from .directives import (
    DEFAULT_DEPRECATION_REASON,  # Predicate; Assertion; Directives Definition; Built-in Directives defined by the Spec; Keyword Args; Constant Deprecation Reason
)
from .directives import (
    GraphQLDeprecatedDirective,
    GraphQLDirective,
    GraphQLDirectiveKwargs,
    GraphQLIncludeDirective,
    GraphQLSkipDirective,
    GraphQLSpecifiedByDirective,
    assert_directive,
    is_directive,
    is_specified_directive,
    specified_directives,
)
from .introspection import (
    SchemaMetaFieldDef,  # Predicate; GraphQL Types for introspection.; "Enum" of Type Kinds; Meta-field definitions.
)
from .introspection import (
    TypeKind,
    TypeMetaFieldDef,
    TypeNameMetaFieldDef,
    introspection_types,
    is_introspection_type,
)

# Common built-in scalar instances.
from .scalars import (
    GRAPHQL_MAX_INT,  # Predicate; Standard GraphQL Scalars; Int boundaries constants
)
from .scalars import (
    GRAPHQL_MIN_INT,
    GraphQLBoolean,
    GraphQLFloat,
    GraphQLID,
    GraphQLInt,
    GraphQLString,
    is_specified_scalar_type,
    specified_scalar_types,
)
from .schema import (
    GraphQLSchema,  # Predicate; Assertion; GraphQL Schema definition; Keyword Args
)
from .schema import GraphQLSchemaKwargs, assert_schema, is_schema

# Validate GraphQL schema.
from .validate import assert_valid_schema, validate_schema


__all__ = [
    "is_schema",
    "assert_schema",
    "assert_name",
    "assert_enum_value_name",
    "GraphQLSchema",
    "GraphQLSchemaKwargs",
    "is_type",
    "is_scalar_type",
    "is_object_type",
    "is_interface_type",
    "is_union_type",
    "is_enum_type",
    "is_input_object_type",
    "is_list_type",
    "is_non_null_type",
    "is_input_type",
    "is_output_type",
    "is_leaf_type",
    "is_composite_type",
    "is_abstract_type",
    "is_wrapping_type",
    "is_nullable_type",
    "is_named_type",
    "is_required_argument",
    "is_required_input_field",
    "assert_type",
    "assert_scalar_type",
    "assert_object_type",
    "assert_interface_type",
    "assert_union_type",
    "assert_enum_type",
    "assert_input_object_type",
    "assert_list_type",
    "assert_non_null_type",
    "assert_input_type",
    "assert_output_type",
    "assert_leaf_type",
    "assert_composite_type",
    "assert_abstract_type",
    "assert_wrapping_type",
    "assert_nullable_type",
    "assert_named_type",
    "get_nullable_type",
    "get_named_type",
    "resolve_thunk",
    "GraphQLScalarType",
    "GraphQLObjectType",
    "GraphQLInterfaceType",
    "GraphQLUnionType",
    "GraphQLEnumType",
    "GraphQLInputObjectType",
    "GraphQLInputType",
    "GraphQLArgument",
    "GraphQLList",
    "GraphQLNonNull",
    "GraphQLType",
    "GraphQLInputType",
    "GraphQLOutputType",
    "GraphQLLeafType",
    "GraphQLCompositeType",
    "GraphQLAbstractType",
    "GraphQLWrappingType",
    "GraphQLNullableType",
    "GraphQLNamedType",
    "GraphQLNamedInputType",
    "GraphQLNamedOutputType",
    "Thunk",
    "ThunkCollection",
    "ThunkMapping",
    "GraphQLArgument",
    "GraphQLArgumentMap",
    "GraphQLEnumValue",
    "GraphQLEnumValueMap",
    "GraphQLField",
    "GraphQLFieldMap",
    "GraphQLInputField",
    "GraphQLInputFieldMap",
    "GraphQLScalarSerializer",
    "GraphQLScalarValueParser",
    "GraphQLScalarLiteralParser",
    "GraphQLArgumentKwargs",
    "GraphQLEnumTypeKwargs",
    "GraphQLEnumValueKwargs",
    "GraphQLFieldKwargs",
    "GraphQLInputFieldKwargs",
    "GraphQLInputObjectTypeKwargs",
    "GraphQLInterfaceTypeKwargs",
    "GraphQLNamedTypeKwargs",
    "GraphQLObjectTypeKwargs",
    "GraphQLScalarTypeKwargs",
    "GraphQLUnionTypeKwargs",
    "GraphQLFieldResolver",
    "GraphQLTypeResolver",
    "GraphQLIsTypeOfFn",
    "GraphQLResolveInfo",
    "ResponsePath",
    "is_directive",
    "assert_directive",
    "is_specified_directive",
    "specified_directives",
    "GraphQLDirective",
    "GraphQLIncludeDirective",
    "GraphQLSkipDirective",
    "GraphQLDeprecatedDirective",
    "GraphQLSpecifiedByDirective",
    "GraphQLDirectiveKwargs",
    "DEFAULT_DEPRECATION_REASON",
    "is_specified_scalar_type",
    "specified_scalar_types",
    "GraphQLInt",
    "GraphQLFloat",
    "GraphQLString",
    "GraphQLBoolean",
    "GraphQLID",
    "GRAPHQL_MAX_INT",
    "GRAPHQL_MIN_INT",
    "is_introspection_type",
    "introspection_types",
    "TypeKind",
    "SchemaMetaFieldDef",
    "TypeMetaFieldDef",
    "TypeNameMetaFieldDef",
    "validate_schema",
    "assert_valid_schema",
]
