name: Performance

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    name: 📈 Benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python with uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Install tox
        run: |
          uv pip install tox tox-uv

      - name: Run benchmarks with CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          mode: instrumentation
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: tox -e py313 -- -k benchmarks --benchmark-enable --codspeed
