name: Performance

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    name: 📈 Benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: "3.13"
          architecture: x64

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-uv uv

      - name: Run benchmarks with CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          mode: instrumentation
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: tox -e py313 -- -k benchmarks --benchmark-enable --codspeed
